float:
  any:
  - base_args:
    - '@metric'
    constructor: FaissHNSW
    disabled: false
    docker_tag: custom-hnsw-faiss
    module: ann_benchmarks.algorithms.faiss_hnsw
    name: hnsw(faiss)
    run_groups:
      M-5:
        arg_groups:
        - M: 5
          efConstruction: 25
        args: {}
        query_args:
        - - 100
          - 200
          - 500
          - 1000
