float:
  any:
  - base_args:
    - '@metric'
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector_bf
    name: pgvector_bf
    run_groups:
      base:
        args: []
        query_args:
        - - 0
