float:
  any:
  - base_args:
    - '@metric'
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      HNSW:
        args:
          M:
          - 5
          efConstruction:
          - 25
        query_args:
        - - 100
          - 200
          - 500
          - 1000
