float:
  any:
  - base_args:
    - '@metric'
    constructor: FaissFlat
    disabled: false
    docker_tag: custom-hnsw-faiss
    module: ann_benchmarks.algorithms.faiss
    name: faiss-flat
    run_groups:
      base:
        args: []
        query_args:
        - - 0
