float:
  any:
  - base_args:
    - '@metric'
    constructor: FaissHNSWPostFilter
    disabled: false
    docker_tag: ann-benchmarks-faiss
    module: ann_benchmarks.algorithms.faiss_hnsw
    name: hnsw(faiss)-post
    run_groups:
      M-16:
        arg_groups:
        - M: 16
          efConstruction: 128
        args: {}
        query_args:
        - - 40
          - 60
          - 80
