float:
  any:
  - base_args:
    - '@metric'
    constructor: FaissIVF
    disabled: false
    docker_tag: custom-hnsw-faiss
    module: ann_benchmarks.algorithms.faiss
    name: faiss-ivf
    run_groups:
      base:
        args:
          clusters:
          - 100
          - 500
        query_args:
        - - 1
          - 5
          - 10
          - 20
          - 50
